stages:
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
    outs:
      - outputs/model.pkl
    params:
      - src/params.py:
          - EnvConfig
          - TrainConfig
    plots:
      - outputs/train_rewards.json:
          cache: false
          template: smooth


  eval:
    cmd: python src/eval.py
    deps:
      - outputs/model.pkl
      - src/eval.py
    params:
      - src/params.py:
          - EnvConfig
          - EvalConfig
    metrics:
      - outputs/metrics.json:
          cache: false
